from django.urls.conf import path

from .views import (AddDepartment, AddDesignation, AddEmployee,
                    AddEmployeeDocument, AddWorkShift, ApproveDocument,
                    ApproveLeaveRequest, AssignEmployeesToShift,
                    AttendanceView, ChangePassword, CloseAttendance,
                    DailyAttendanceView, Dashboard, DenyLeaveRequest, EditDepartment,
                    EditDesignation, EditEmployee, EditWorkShift,
                    EmployeeAttendance, EmployeeList, EmployeeProfile,
                    LeaveRequestList, ListDepartment, ListDesignation,
                    ListWorkShift, RemoveDepartment, RemoveDesignation,
                    RemoveDocument, RemoveEmployee, RemoveWorkShift,
                    RequestLeave, Schedule, ShiftReport, ToggleActiveStatus,
                    UpdateAttendance, ViewLeaveRequest)

app_name = 'staff'
urlpatterns = [
    path('add-department', AddDepartment.as_view(), name='add_department'),
    path('edit-department/<int:dep_id>', EditDepartment.as_view(), name='edit_department'),
    path('remove-department/<int:dep_id>', RemoveDepartment.as_view(), name='remove_department'),
    path('list-departments', ListDepartment.as_view(), name='list_department'),
    path('add-designation', AddDesignation.as_view(), name='add_designation'),
    path('edit-designation/<int:desig_id>', EditDesignation.as_view(), name='edit_designation'),
    path('list-designation', ListDesignation.as_view(), name='list_designation'),
    path('remove-designation/<int:desig_id>', RemoveDesignation.as_view(), name='remove_designation'),
    path('employee-list', EmployeeList.as_view(), name='list_employee'),
    path('attendance', AttendanceView.as_view(), name='attendance' ),
    path('attendance/today', DailyAttendanceView.as_view() , name='daily_attendance' ),
    path('attendance/<str:emp_id>', EmployeeAttendance.as_view(), name='employee_attendance'),
    path('attendance/update/<int:id>', UpdateAttendance.as_view(), name='update_attendance'),
    path('add-employee', AddEmployee.as_view(), name='add_employee'),
    path('edit-employee/<str:emp_id>', EditEmployee.as_view(), name='edit_employee'),
    path('add-doc/<int:id>', AddEmployeeDocument.as_view(), name='add_employee_document'),
    path('change-password/<int:id>', ChangePassword.as_view(), name='change_password'),
    path('employee/<int:id>', EmployeeProfile.as_view(), name='view_employee'),
    path('active-status/<int:id>', ToggleActiveStatus.as_view(), name='active_status'),
    path('request-leave/<int:id>', RequestLeave.as_view(), name='request_leave'),
    path('request-list', LeaveRequestList.as_view(), name='leave_request_list'),
    path('approve-leave/<int:id>', ApproveLeaveRequest.as_view(), name='approve_leave'),
    path('deny-leave/<int:id>', DenyLeaveRequest.as_view(), name='deny_leave'),
    path('remove-employee/<int:id>', RemoveEmployee.as_view(), name='remove_employee'),
    path('remove-doc/<int:id>', RemoveDocument.as_view(), name='remove_document'),
    path('add-workshift', AddWorkShift.as_view(), name='add_workshift'),
    path('edit-workshift/<int:id>', EditWorkShift.as_view(), name='edit_workshift'),
    path('list-workshift', ListWorkShift.as_view(), name='list_workshift'),
    path('workshift/remove/<int:id>', RemoveWorkShift.as_view(), name='remove_workshift'),
    path('aetoshift/<int:id>', AssignEmployeesToShift.as_view(), name='assign_shift'),
    path('shift-report', ShiftReport.as_view(), name='shift_report' ),
    path('approve-document/<int:id>', ApproveDocument.as_view(), name='approve_document'),
    path('view-lr/<int:id>', ViewLeaveRequest.as_view(), name='view_leave_request'),
    path('close-att', CloseAttendance.as_view(), name='finish_work'),
    path('schedule', Schedule.as_view(), name='schedule'),
    path('dashboard', Dashboard.as_view(), name='dashboard'),
]
